tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/selfsigned.crt
        keyFile: /etc/traefik/certs/selfsigned.key

http:
  routers:
    traefik:
      rule: "Host(`traefik.localhost`)"
      entryPoints: websecure
      service: api@internal
      tls: true

    frontend:
      rule: "Host(`frontend.localhost`)"
      entryPoints: websecure
      service: frontend-service
      tls: true

    backend:
      rule: "Host(`backend.localhost`)"
      entryPoints: websecure
      service: backend-service
      tls: true

    email-service:
      rule: "Host(`email.localhost`)"
      entryPoints: websecure
      service: email-service-service
      tls: true

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://micro-frontend-container:80"

    backend-service:
      loadBalancer:
        servers:
          - url: "http://micro-backend-container:80"

    email-service-service:
      loadBalancer:
        servers:
          - url: "http://micro-email-container:80"
