providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: true
  debug: true

#Logging
log:
  # level: INFO
  level: DEBUG

#Entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    # tls:
    #   certResolver: myresolver

# ACME Configuration
certificatesResolvers:
  le:
    acme:
      email: ahmettoguz@hotmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
      tlsChallenge: false
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
