api:
  dashboard: true
  insecure: true
#Enable Docker Provider
providers:
  docker:
    watch: true
    exposedByDefault: false
    swarmMode: false
  file:
    filename: /etc/traefik/traefik_dynamic.yml

#Logging
log:
  level: INFO

#Entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
