tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/fullchain.pem
        keyFile: /etc/traefik/certs/privkey.pem

http:
  routers:
    traefik:
      rule: "Host(`sendsphere.com.tr`) && PathPrefix(`/traefik`) || (PathPrefix(`/api`) || PathPrefix(`/dashboard`)) && HeaderRegexp(`Referer`, `(?i).*traefik.*`)"
      entryPoints: websecure
      service: api@internal
      tls: true
      middlewares:
        - strip-traefik

    frontend:
      rule: "Host(`sendsphere.com.tr`)"
      entryPoints: websecure
      service: frontend-service
      tls: true

    backend:
      rule: "Host(`sendsphere.com.tr`) && PathPrefix(`/backend`) || PathPrefix(`/sw`) && HeaderRegexp(`Referer`, `(?i).*backend.*`)"
      entryPoints: websecure
      service: backend-service
      tls: true
      middlewares:
        - strip-backend

    email-service:
      rule: "Host(`sendsphere.com.tr`) && PathPrefix(`/email`) || PathPrefix(`/sw`)"
      entryPoints: websecure
      service: email-service-service
      tls: true
      middlewares:
        - strip-email

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://micro-frontend-container:80"
          - url: "http://host.docker.internal:5173"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "6s"

    backend-service:
      loadBalancer:
        servers:
          - url: "http://micro-backend-container:80"
          - url: "http://host.docker.internal:8081"
        healthCheck:
          path: /health-check
          interval: "10s"
          timeout: "6s"

    email-service-service:
      loadBalancer:
        servers:
          - url: "http://micro-email-container:80"
          - url: "http://host.docker.internal:8082"
        healthCheck:
          path: /health-check
          interval: "10s"
          timeout: "6s"

  middlewares:
    strip-traefik:
      stripPrefix:
        prefixes:
          - "/traefik"
    strip-backend:
      stripPrefix:
        prefixes:
          - "/backend"
    strip-email:
      stripPrefix:
        prefixes:
          - "/email"
