api:
  dashboard: true
  insecure: true
#Enable Docker Provider
providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/
    filename: traefik_dynamic.yml

#Logging
log:
  # level: INFO
  level: DEBUG

#Entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
