providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: true
  debug: true

log:
  # level: INFO
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  lets:
    acme:
      email: <your email address>
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
