version: "3.8"
services:
  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      # - 9000:8080 # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik-conf/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./cert/selfsigned.crt:/etc/traefik/certs/selfsigned.crt
      - ./cert/selfsigned.key:/etc/traefik/certs/selfsigned.key

  frontend:
    build: ../Micro-Frontend/
    image: micro-frontend-image
    container_name: micro-frontend-container
    # ports:
    #   - "8000:80"

  backend:
    build: ../Micro-Backend/
    image: micro-backend-image
    container_name: micro-backend-container
    # ports:
    #   - "8081:80"

  email-service:
    build: ../Micro-Email-Service/
    image: micro-email-image
    container_name: micro-email-container
    # ports:
    #   - "8082:80"
