version: '3.8'
services:

  frontend:
    build: ../Micro-Frontend/
    image: micro-frontend-image
    container_name: micro-frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ../Micro-Backend/
    image: micro-backend-image
    container_name: micro-backend-container
    ports:
      - "8081:8081"

  email-service:
    build: ../Micro-Email-Service/
    image: micro-email-image
    container_name: micro-email-container
    ports:
      - "8082:8082"
    depends_on:
      - backend
      - frontend